import $ from 'jquery';

const CommonStyles = {
  filters: {
    toolbar: {
      backgroundColor: 'transparent',
      width: '100%',
      padding: '0',
      height: 40,
      justifyContent: 'flex-end',
    },
    title: {
      color: 'rgba(0, 0, 0, 0.541176)',
      fontSize: 15,
      paddingRight: 8,
      lineHeight: '40px',
    },
    icon: {
      width: 36,
      height: 36,
      padding: 0,
    },
  },
  checkbox: {
    labelStyle: {
      color: '#A5A5A5',
      fontWeight: 'bold',
    },
    iconStyle: {
      width: 24,
      left: 0,
    },
    inputStyle: {
      width: 24,
    },
    style: {
      width: '100%',
      margin: 'auto',
      textAlign: 'left',
      paddingLeft: 0,
    },
  },
  dashBubblesMenu: {
    addBubbleCircleStyle: {
      marginRight: 4,
      verticalAlign: 'middle',
    },
    addBubbleIconStyle: {
      color: '#949494',
      backgroundColor: 'transparent',
      width: 24,
      height: 24,
      verticalAlign: '-30%',
      marginLeft: 5,
      marginRight: 12,
    },
    bubbleImageStyle: {
      width: 35,
      height: 35,
      borderRadius: 999,
      marginRight: 4,
      backgroundColor: 'transparent',
    },
  },
  outside: {
    buttonLabelColor: '#FFFFFF',
    buttonHoverColor: '#308775',
    buttonBackgroundColor: '#62db95',
    buttonHowitworks: 'rgba(255, 255, 255, 0.4)',
    emailAddressStyle: {
      float: 'left',
      height: '58px',
      lineHeight: '30px',
      marginLeft: '20px',
      fontSize: '1.5em',
    },
    textStyle: {
      width: '100%',
      height: 'auto',
      marginBottom: '20px',
    },
    signButtonStyle: {
      borderRadius: '4px',
      height: '48px',
      width: '100%',
      margin: '16px 0 0 0',
    },
    signButtonLabelStyle: {
      fontSize: '1.1em',
      color: '#fff',
      fontWeight: '400',
      boxShadow: 'none',
      textTransform: 'none',
      padding: '0px 26px',
      lineHeight: '44px',
    },
    newsButtonLabelStyle: {
      fontSize: '1.1em',
      color: '#fff',
      fontWeight: '400',
      boxShadow: 'none',
      textTransform: 'none',
      padding: '0px 13px',
    },
    paperStyle: {
      borderRadius: '4px',
      boxShadow: '0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24)',
      transition: 'all 0.3s cubic-bezier(.25,.8,.25,1)',
      maxWidth: '420px',
      width: '100%',
      margin: '0 auto',
      textAlign: 'center',
      display: 'inline-block',
      padding: '50px',
    },
    inputStyle: {
      border: '1px solid #dfdfdf',
      borderRadius: '4px',
      padding: '18px 0 0 18px',
      height: '56px',
      marginTop: '0',
    },
    labelStyle: {
      paddingLeft: '25px',
      fontSize: '16px',
      top: '18px',
      lineHeight: '56px',
      transform: 'scale(1) translate(0px, -16px)',
    },
    labelFocusStyle: {
      top: '18px',
    },
    errorStyle: {
      textAlign: 'left',
      position: 'static',
      bottom: '0',
      marginTop: '5px',
    },
    styleRadioButton: {
      textAlign: 'left',
      display: 'inline-block',
      width: 'auto',
      marginRight: '20px',
    },
    inputSelectStyle: {
      border: '1px solid #dfdfdf',
      borderRadius: '4px',
      width: '100%',
      height: '56px',
      marginTop: '0',
      fontSize: '15px',
      paddingLeft: '18px',
    },
    selectStyle: {
      width: '100%',
      height: 'auto',
      display: 'block',
      textAlign: 'left',
      marginBottom: '20px',
    },
    selectDateStyle: {
      width: '30.37%',
      height: 'auto',
      display: 'inline-block',
      textAlign: 'left',
    },
    interestsStyle: {
      width: '100%',
      height: 'auto',
    },
    iconSecelctStyle: {
      right: '-4px',
      top: '4px',
      padding: '0px',
    },
    menuItemsStyle: {
      padding: '0 16px',
    },
  },
  userBubblz: {
    containerStyle: {
      padding: 50,
      boxShadow: '0px 0px 14px 0px rgba(181, 181, 181, 0.15)',
      backgroundColor: '#ffffff',
    },
    bubbleStyle: {
      minHeight: 95,
      padding: '0 0 15px 105px',
      position: 'relative',
    },
    bubbleBottomBorderStyle: {
      marginBottom: 15,
      borderBottom: '1px solid #f7f7f7',
    },
    avatarStyle: {
      display: 'block',
      position: 'absolute',
      width: 80,
      height: 80,
      borderRadius: 999,
      left: 0,
      top: 0,
    },
    titleStyle: {
      fontSize: 14,
      color: '#5ed28f',
      marginBottom: 5,
    },
    categoryStyle: {
      fontSize: 16,
      marginBottom: 12,
    },
    grayColor: '#d4d6d9',
    iconStyle: {
      width: 20,
      height: 20,
      verticalAlign: 'middle',
    },
    statStyle: {
      fontSize: 12,
      color: '#d4d6d9',
    },
    joinButtonContainerStyle: {
      position: 'absolute',
      right: 0,
      top: 10,
    },
  },
  userProfile: {
    loaderWrapperStyle: {
      width: 120,
      padding: '3px 0 6px',
      border: '1px solid #f0f0f1',
      borderRadius: 4,
      textAlign: 'center',
    },
    dashTabContainerStyle: {
      marginBottom: 20,
    },
    dashTabStyle: {
      color: '#e1e1e1',
      fontSize: 18,
      padding: '6px 17px',
      margin: '0 10px 10px 0',
      display: 'inline-block',
    },
    dashTabActiveStyle: {
      color: '#ffffff',
      backgroundColor: '#ffffff',
    },
    dashTabInactiveStyle: {
    },
    forceFonts: {
      fontFamily: 'Arimo, sans serif',
    },
  },
  bubble: {
    bubbleNameStyle: {
      textAlign: 'left',
      fontSize: 16,
      marginTop: 15,
    },
    inviteButtonContainerStyle: {
      marginTop: 20,
    },
    manageLinksContainerStyle: {
      marginTop: 35,
    },
    paperStyle: {
      margin: 0,
      textAlign: 'center',
      padding: 20,
      background: 'transparent',
    },
    inputStyle: {
      border: '1px solid #dfdfdf',
      borderRadius: '4px',
      padding: '18px 0 0 18px',
      height: '56px',
      marginTop: '0',
    },
    labelStyle: {
      paddingLeft: '25px',
      fontSize: '15px',
      top: '18px',
    },
    labelFocusStyle: {
      top: '30px',
    },
    errorStyle: {
      textAlign: 'left',
      position: 'static',
      bottom: '0',
      paddingLeft: '0',
      marginTop: '5px',
    },
    inviteButtonStyle: {
      height: '48px',
      marginBottom: 20,
    },
    inviteButtonLabelStyle: {
      fontSize: '1.2em',
      textTransform: 'none',
      padding: '0px 30px',
      lineHeight: '50px',
      color: '#ffffff',
    },
    buttonContainerStyle: {
      textAlign: 'center',
    },
  },
  bubbleMembers: {
    titleStyle: {
      fontSize: 15,
      marginBottom: 15,
    },
    avatarContainerStyle: {
      marginRight: 12,
      marginBottom: 12,
      position: 'relative',
      float: 'left',
    },
  },
  bubbleManage: {
    containerStyle: {
      padding: '80px 35px 40px',
      boxShadow: '0px 0px 14px 0px rgba(181, 181, 181, 0.15)',
      backgroundColor: '#ffffff',
      position: 'relative',
    },
    topbarStyle: {
      position: 'absolute',
      left: 0,
      top: 0,
      right: 0,
      padding: '16px 25px',
      background: '#fbfbfb',
    },
    userStyle: {
      minHeight: 80,
      padding: '5px 20px 15px 85px',
      position: 'relative',
    },
    userBottomBorderStyle: {
      marginBottom: 15,
      borderBottom: '1px solid #f7f7f7',
    },
    avatarStyle: {
      display: 'block',
      position: 'absolute',
      width: 60,
      height: 60,
      borderRadius: 999,
      left: 0,
      top: 0,
    },
    usernameStyle: {
      fontSize: 16,
    },
    userTitleStyle: {
      fontSize: 12,
      marginBottom: 10,
    },
    menuContainerStyle: {
      position: 'absolute',
      right: 0,
      top: 0,
    },
    menuItemStyle: {
      fontSize: '13px',
      lineHeight: '30px',
      paddingTop: 5,
      paddingBottom: 5,
      minHeight: 30,
    },
    iconButtonStyle: {
      verticalAlign: 'middle',
      lineHeight: 1,
    },
  },
  iconStyle: {
    verticalAlign: '-30%',
    color: '#949494',
    marginRight: 4,
    width: 20,
    height: 20,
  },
  iconColor: '#3c455c',
  dividerStyle: {
    backgroundColor: '#f2f1f1',
    marginTop: 6,
    marginBottom: 6,
  },
  sidebar: {
    root: {
      position: $(window).width() > 480 ? 'fixed' : 'absolute',
      top: 0,
      zIndex: $(window).width() > 480 ? 190 : 10,
      width: '16rem',
      maxWidth: '260px',
      padding: '1rem 0.75rem',
      boxShadow: '1px 0px 8px 0px #ddd',
    },
    sidebar: {
      position: 'relative',
      left: '12px',
      top: -5,
      width: '100%',
      transition: 'transform .3s ease-out',
      WebkitTransition: '-webkit-transform .3s ease-out',
      willChange: 'transform',
      overflowY: 'hidden',
      boxShadow: 'none',
      transform: 'translateX(0)!important',
      padding: 0,
    },
    content: {
      position: 'relative',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      overflow: 'auto',
      transition: 'left .3s ease-out, right .3s ease-out',
      boxShadow: 'none',
    },
    overlay: {
      zIndex: 1,
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      opacity: 0,
      visibility: 'hidden',
      transition: 'opacity .3s ease-out',
      backgroundColor: 'rgba(0,0,0,0.1)',
      boxShadow: 'none',
    },
    dragHandle: {
      zIndex: 1,
      position: 'fixed',
      top: 0,
      bottom: 0,
    },
  },
  presence: {
    statusStyle: {
      width: 12,
      height: 12,
      borderRadius: 999,
      position: 'absolute',
      left: 0,
      bottom: 0,
    },
    userProfileStatusStyle: {
      width: 12,
      height: 12,
      borderRadius: 999,
      marginRight: 5,
      display: 'inline-block',
    },
    offlineStyle: {
      background: '#bbb',
    },
    onlineStyle: {
      background: '#5ed28f',
    },
  },
  dialog: {
    root: {
      padding: 0,
    },
    overlay: {
      padding: 0,
    },
    content: {
      padding: 0,
      maxWidth: 'none',
      width: '50%',
      minWidth: $(window).width() > 480 ? '500px' : '320px',
      transform: $(window).width() > 480 ? 'translate(0px, 20px)' : 'translate(0px, 50px)',
    },
    gallery_content: {
      padding: 0,
      maxWidth: 'none',
      width: $(window).width() > 480 ? '90%' : '95%',
      transform: 'translate(0px, 20px)',
    },
    body: {
      padding: 0,
    },
    title: {
      margin: 0,
      padding: '16px 24px 16px',
      color: '#555',
      fontSize: '1.3em',
      lineHeight: '20px',
      paddingBottom: '16px',
      borderBottom: '1px solid #efefef',
      textAlign: 'center',
    },
  },
  widget: {
    containerStyle: {
      boxShadow: '0px 0px 14px 0px rgba(181, 181, 181, 0.15)',
      backgroundColor: '#ffffff',
      position: 'relative',
    },
    rightButtonStyle: {
      float: 'right',
      textTransform: 'none',
      backgroundColor: '#61d894',
      color: '#ffffff',
      padding: '6px 16px',
      borderRadius: '4px',
      margin: '4px 4px 0 0',
    },
    actionButtonIconStyle: {
      textTransform: 'none',
      backgroundColor: '#61d894',
      color: '#ffffff',
      padding: '6px 16px 6px 12px',
      borderRadius: '4px',
      display: 'inline-block',
    },
    deleteButtonIconStyle: {
      textTransform: 'none',
      backgroundColor: '#D97575',
      color: '#ffffff',
      padding: '6px 16px 6px 12px',
      borderRadius: '4px',
      display: 'inline-block',
    },
  },
  common: {
    boxStyle: {
      boxShadow: '0px 0px 14px 0px rgba(181, 181, 181, 0.15)',
      padding: '155px 15px 240px',
      textAlign: 'center',
      backgroundColor: '#ffffff',
    },
    svgStyle: {
      maxWidth: 70,
      width: '100%',
    },
    textStyle: {
      fontSize: 18,
      maxWidth: 450,
      margin: '50px auto 0',
      width: '100%',
    },
  },
};

export default CommonStyles;
